# SPDX-FileCopyrightText: Copyright (c) 2026 Maxim Khrichtchatyi
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: shellcheck
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  shellcheck:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get update && sudo apt-get install -y shellcheck
      - run: shellcheck install.sh tests/*.sh
